# Generated by Django 4.2.4 on 2023-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qrcode',
            field=models.FileField(upload_to='qrcode/'),
        ),
    ]
